apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jira
spec:
  selector:
    matchLabels:
      app: jira
  serviceName: jira
  replicas: 1
  template:
    metadata:
      labels:
        app: jira
    spec:
      serviceAccountName: jira
      securityContext:
        runAsUser: 0
        fsGroup: 2
      containers:
      - name: jira
        image: "cptactionhank/atlassian-jira-software:7.10.1"
        imagePullPolicy: IfNotPresent
        env:
          - name: X_PROXY_NAME
            value: "jira.mydomain.com"
          #- name: X_PROXY_PORT
            #value: "443"
          #- name: X_PROXY_SCHEME
            #value: "https"
          - name: JAVA_OPTS
            value: "-Xmx1024m -Xms1024m -XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m -Djira.websudo.is.disabled=true"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 3
        volumeMounts:
          - name: data
            mountPath: /var/atlassian/jira
        resources:
          limits:
            memory: 2560Mi
          requests:
              memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        env: prod
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast" # StorageOS storageClass 
      resources:
        requests:
          storage: 10Gi

