apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluence
spec:
  selector:
    matchLabels:
      app: confluence
  serviceName: jira
  replicas: 1
  template:
    metadata:
      labels:
        app: confluence
    spec:
      serviceAccountName: jira
      securityContext:
        runAsUser: 0
        fsGroup: 2002
      containers:
        - name: atlassian-confluence
          image: "atlassian/confluence-server:7.0.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: CATALINA_CONNECTOR_PROXYNAME
              value: "confluence.example.com"
            #- name: CATALINA_CONNECTOR_PROXYPORT
              #value: "443"
            #- name: CATALINA_CONNECTOR_SCHEME
              #value: "https"
            #- name: CATALINA_CONNECTOR_SECURE
              #value: "true"
            - name: JVM_MINIMUM_MEMORY
              value: "1024m"
            - name: JVM_MAXIMUM_MEMORY
              value: "1024m"
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              value: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m  -Dsynchrony.memory.max=0m"
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
            - name: synchrony
              containerPort: 8091
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /var/atlassian/application-data/confluence
          resources:
            limits:
              memory: 2560Mi
            requests:
              memory: 1536Mi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast" # StorageOS storageClass 
      resources:
        requests:
          storage: 10Gi
