---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: backup-example
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index index.html;
            autoindex on;
        }
        
        location /dir {
            alias /usr/share/nginx/html;
            autoindex on;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
