apiVersion: v1
kind: Secret
metadata:
  name: "aws-creds"
  labels:
    app: "backup"
type: "Opaque"
stringData:
  credentials: |-
    [default]
    aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
    aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

