apiVersion: v1
kind: ConfigMap
metadata:
    name: rsync-config
data:
    rsyncd.conf: |
      [global]
      charset = utf-8
      max connections = 8
      reverse lookup = no

      [share]
      path = /share
      read only = yes
      auth users = user
      secrets file = /etc/rsyncd.secrets

