apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-storageos
  labels:
    app: prometheus-operator
spec:
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
#  securityContext:
#    fsGroup: 2000
#    runAsNonRoot: true
#    runAsUser: 1000
#  storage:
#    volumeClaimTemplate:
#      spec:
#        storageClassName: fast
#        resources:
#          requests:
#            storage: 10Gi
